Repository optimizely/go-sdk, pull requests merged in 2020-07, with the labels that each got.

#277 ci: hook fps on travis
  .travis.yml
Labels: :robot: 20 hrs

#284 ci: testify on go 1.10 causing problem
  .travis.yml
Labels: :robot: 12 hrs

#283 ci: Run source clear only on cron and before linting and tests
  .travis.yml
Labels: :robot: 4 hrs
